export const cargoOptions = [
  { value: "SC", label: "SC - Sem Cargo" },
  { value: "VM", label: "VM - Venerável Mestre" },
  { value: "EXVM", label: "ExVM - Ex-Venerável Mestre" },
  { value: "1VIG", label: "1VIG - 1º Vigilante" },
  { value: "2VIG", label: "2VIG - 2º Vigilante" },
  { value: "ORAD", label: "ORAD - Orador" },
  { value: "SECR", label: "SECR - Secretário" },
  { value: "TESO", label: "TESO - Tesoureiro" },
  { value: "CHAN", label: "CHAN - Chanceler" },
  { value: "MC", label: "MC - Mestre de Cerimônias" },
  { value: "MCA", label: "MCA - Mestre de Cerimônias Adjunto" },
  { value: "HOSP", label: "HOSP - Hospitaleiro" },
  { value: "CAP", label: "CAP - Capelão" },
  { value: "STWA", label: "STWA - Stuart" },
  { value: "MORD", label: "MORD - Mordomo" },
  { value: "1DIC", label: "1DIC - 1º Diácono" },
  { value: "2DIC", label: "2DIC - 2º Diácono" },
  { value: "PESP", label: "PESP - Porta Espadas" },
  { value: "PEST", label: "PEST - Porta Estandarte" },
  { value: "1EXP", label: "1EXP - Primeiro Experto" },
  { value: "2EXP", label: "2EXP - Segundo Experto" },
  { value: "GT", label: "GT - Guarda do Templo" },
  { value: "COBR", label: "COBR - Cobridor" },
  { value: "ARQT", label: "ARQT - Arquiteto" },
  { value: "MBAN", label: "MBAN - Mestre de Banquetes" },
  { value: "MHAR", label: "MHAR - Mestre de Harmonia" },
  { value: "BIBL", label: "BIBL - Bibliotecário" },
  { value: "CEXT", label: "CEXT - Cobridor Externo" },
] as const;

export type MemberCargoValue = (typeof cargoOptions)[number]["value"];
